### ISSUE TITLE
Example of sticky header and footer

### ISSUE THREAD

**Issue by cheahkhing** [ghinda/gridlayout#1]
Hi, the example didn't show how we can achieve a sticky / fixed header / footer that always shown when scrolling on the content.
This is quite common nowadays as most of the navbar on top are fixed and sticky.
It would be really helpful if you could show an example.

**Comment by ghinda** [comment]
Hi. The sticky footer demo is a solution to a different CSS layout problem. Here are other solutions:

http://mystrd.at/modern-clean-css-sticky-footer/
https://css-tricks.com/snippets/css/sticky-footer/
http://ryanfait.com/sticky-footer/

The fixed header/footer you're looking for can be achieved using `position: fixed`. It's not related to the grid, that's why it's not included.

If you want the header or footer to "stick" to the top or bottom of the screen only after you've scrolled beyond a certain point, you'll have to use a JavaScript library similar to:
http://foundation.zurb.com/docs/components/magellan.html
