### ISSUE TITLE
SCSS?

### ISSUE THREAD

**Issue by aolko** [ghinda/gridlayout#2]
SCSS version, please?
For those who prefer to declare rows and columns in-styles, not in html

**Comment by ghinda** [comment]
Hi,

I'm using Stylus for the CSS, so I don't plan on creating a separate Sass version. 
But you can still use Sass's `@extend`.

Rename the `gridlayout.css` file to `gridlayout.scss`.
In your Sass file, import gridlayout with `@import 'gridlayout'`.

Then you can `@extend` your classes with the gridlayout classes.

```
.your-custom-grid {
  @extend .gl;
}

.your-custom-col {
  @extend .gl-cell;
}
```

Hope this helps!

**Comment by aolko** [comment]
well, maybe a way for more [flexible.gs](http://flexible.gs/learn/col-row/?preprocessor=scss#col-row-scss)-like approach?

**Comment by ghinda** [comment]
Problem is, that would require switching to Sass and rewriting all the classes as mixins. 

I gave up Sass for Stylus a while ago, and my life has been better ever since. :grinning: I'm joking, but I don't want to maintain two separate versions of it.

If you'd like to port the Sass version, I'd hapilly give you commit access to the repo and include the `scss` file.
